### ISSUE TITLE
dash_server_HotDASH problem

### ISSUE THREAD

**Issue by YiRuChenbilibili** [SatadalSengupta/hotdash#2]
The dash_server_HotDASH.py in abr_server only return bitrate decision like Pensieve server. How can I use my trained model and return prefetch decision to  hotdash.js? I am just a student unfamiliar with dash and I am trying to test the model over mahimahi, but I don't know how to return the prefetch decision and let the dash.js to achieve it. It's not in the code as well.

**Comment by SatadalSengupta** [comment]
Hi, it seems that I goofed something up while pushing the final version of the code to GitHub. The code that I was running for my experiments had this feature (of returning prefetch decisions). I will try to add this feature to the GitHub code as soon as I can. Meanwhile, please try doing it yourself if you can - it shouldn't take a lot of effort in my estimate - please shoot your questions here if you face roadblocks while doing the same.

**Comment by YiRuChenbilibili** [comment]
Thank you very much. Actually, I tried my best to do it by myself. But.....emmmm, I know it is a lot for me to learn, I will contiune trying and still looking forward to the final version of the code. Thanks again.

**Comment by YiRuChenbilibili** [comment]
Sorry to interupt again. I can finish a Hotdash server on my own, if only the server can get enough information. The problem is that，the"dash.all.debug.js"cannot return Hotspot chunk information. I find it can only return the information which Pensieve and MPC needs. What can I do about this?

**Comment by YiRuChenbilibili** [comment]
Sorry to interupt again. I can finish a Hotdash server on my own，if only the dash can give back the right information. I found that “dash.all.debug.js” cannot return the Hotspot chunk information，it can only return the information that Pensieve and MPC needs. What can I do now?

**Comment by YiRuChenbilibili** [comment]
Sorry to interupt again. I can finish a Hotdash server on my own，if only the dash can give back the right information. I found that “dash.all.debug.js” cannot return the Hotspot chunk information，it can only return the information that Pensieve and MPC needs. And I also don't know where to put my prefetch decision...What can I do now?

**Comment by YiRuChenbilibili** [comment]
Sorry, but I am afraid I cannot finish it. I found that ‘dash.all.min.js' do not have the prefetch module.Is dash.all.min.js or dash.all.debug.js the final version of hotdash.js?
This is the code in dash.all.debug.js:
                xhr.open("POST", "http://localhost:" + portno, false);
                xhr.onreadystatechange = function () {
                    if (xhr.readyState == 4 && xhr.status == 200) {
                        console.log("GOT RESPONSE:" + xhr.responseText + "---");
                        if (xhr.responseText != "REFRESH") {
                            quality = parseInt(xhr.responseText, 10);
                        } else {
                            document.location.reload(true);
                        }
                    }
                };
                var bufferLevelAdjusted = buffer - 0.15 - 0.4 - 4;
                var data = { 'nextChunkSize': next_chunk_size(lastRequested + 1), 'lastquality': lastQuality, 'buffer': buffer, 'bufferAdjusted': bufferLevelAdjusted, 'bandwidthEst': bandwidthEst, 'lastRequest': lastRequested, 'RebufferTime': rebuffer, 'lastChunkFinishTime': lastHTTPRequest._tfinish.getTime(), 'lastChunkStartTime': lastHTTPRequest.tresponse.getTime(), 'lastChunkSize': last_chunk_size(lastHTTPRequest) };
                xhr.send(JSON.stringify(data));
                console.log("QUALITY RETURNED IS: " + quality);
                var returnedQuality = getFinalQuality(quality, lastRequested + 1, isHotspotFragment);
                console.log(algoStr + " --> Next index: " + String(lastRequested + 1) + "; Quality: " + String(returnedQuality));
                return returnedQuality;
It's for Pensieve，MPC and HotDASH. Where should I put the prefetch decision？
Is that possible for me to have a look at the final version of the code？
